### ISSUE TITLE
A little query

### ISSUE THREAD

**Issue by SpigotRCE** [spawnmason/randar-explanation#6]
Why would minecraft try to generate a mansion on the pre-exsisting chunks when loading????

**Comment by thelampgod** [comment]
Good question 😄
There's no reason for that check to run on already generated chunks, but Minecraft don't caree

**Comment by SpigotRCE** [comment]
Minecraft moment

**Comment by SpigotRCE** [comment]
Minecraft moment, third party servers like paper should optimize that too xd
